server:
  port: 8080
spring:
  application:
    name: MDS-MONGO-MYSQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: P@ssw0rd
    url: jdbc:mysql://169.254.153.55:3306/mds_server_deploy?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
      auto-commit: true
  data:
    mongodb:
      uri: mongodb://169.254.153.55:27017/mds_server_sheng
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy